#Comment: objects_count should be >= than statements_count + conditions_count.
#Comment: conditions_count should be >= than questions_count
tasks_count: 1
statements_count: 2
questions_count: 2
conditions_count: 6
objects_count: 8
reuse_count: [1, 5]

#Comment: Filenames shouldn't be empty.
objects_file_name: "objects.txt"
actions_file_name: "actions.txt"

#Comment: If you do not want to receive the program output to a file, put empty string to field.
output_file_name: ""
